//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATA_KOMTEK
    {
        public long id_data { get; set; }
        public string data_1 { get; set; }
        public string data_2 { get; set; }
        public string data_3 { get; set; }
        public string data_4 { get; set; }
        public string data_5 { get; set; }
        public string data_6 { get; set; }
        public string data_7 { get; set; }
        public string data_8 { get; set; }
        public string data_9 { get; set; }
        public string data_10 { get; set; }
        public string data_11 { get; set; }
        public string data_12 { get; set; }
        public string data_13 { get; set; }
        public string data_14 { get; set; }
        public string data_15 { get; set; }
    }
}
